In [2]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [4]:
my_list

[1, 2, 3, 4, 5]

In [5]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [7]:
my_matrix = [[1,3,5],[3,5,7],[2,4,6]]
my_matrix

[[1, 3, 5], [3, 5, 7], [2, 4, 6]]

In [8]:
np.array(my_matrix)

array([[1, 3, 5],
       [3, 5, 7],
       [2, 4, 6]])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

zeros and ones
Generate arrays of zeros or ones

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

linspace

Return evenly spaced numbers over a specified interval.

In [19]:
np.linspace(1,9,3)

array([1., 5., 9.])

In [21]:
np.linspace(0,100,50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

eye
Creates an identity matrix

In [25]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

Random
Numpy also has lots of ways to create random number arrays:

rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0,1].

In [29]:
oneD_array = np.random.rand(5)
print('1D array with random values: \n ', oneD_array)

1D array with random values: 
  [0.6160556  0.07685844 0.82499583 0.83371838 0.35922012]


In [33]:
twoD_array = np.random.rand(3,5)
print('2D array with random values: \n ', twoD_array)

2D array with random values: 
  [[0.94393259 0.51917794 0.99788095 0.55100293 0.27921233]
 [0.33788577 0.24448657 0.79199743 0.81504996 0.92928294]
 [0.07053328 0.50814216 0.38900538 0.75873146 0.93851859]]


In [40]:
threeD_array = np.random.rand(3,3,2)
print('3D array with random values: \n ', threeD_array)

3D array with random values: 
  [[[0.14512772 0.39106191]
  [0.0704527  0.20102863]
  [0.48843371 0.13227426]]

 [[0.37727568 0.70566391]
  [0.65893813 0.51311528]
  [0.74088543 0.30937355]]

 [[0.49297107 0.68188079]
  [0.99479788 0.15349439]
  [0.78711576 0.02708329]]]


# randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [50]:
np.random.randn(5)

array([ 0.48837424,  0.51222683, -0.10111272,  1.28963177,  1.37139889])

In [51]:
np.random.randn(5,5)

array([[ 0.7225271 ,  1.17928841, -0.77979481, -0.04664487,  0.83009709],
       [ 0.23998246, -1.63096092, -1.88343842, -0.08927901, -0.39253184],
       [-0.40049372, -1.597183  ,  0.1779925 , -0.28118035, -1.58287151],
       [-0.25768512,  0.49052767,  1.55772722,  0.73563565,  0.29549948],
       [ 0.58972907,  0.60573705, -0.72780325,  0.54664802, -0.36680413]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [3]:
np.random.randint(1,100)

39

In [5]:
np.random.randint(1,100,15)

array([99, 82, 94, 82, 37, 13,  4, 20,  9, 79, 12, 90, 79, 76, 83])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [10]:
arr = np.arange(1,26)
rand_arr = np.random.randint(1,100,10)

In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [13]:
rand_arr

array([39,  7, 55, 55, 59, 37, 90, 20, 58, 98])

## Reshape
Returns an array containing the same data with a new shape.

In [14]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
rand_arr.reshape(5,2)

array([[39,  7],
       [55, 55],
       [59, 37],
       [90, 20],
       [58, 98]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [20]:
rand_arr

array([39,  7, 55, 55, 59, 37, 90, 20, 58, 98])

In [21]:
rand_arr.min()

7

In [22]:
rand_arr.max()

98

In [23]:
rand_arr.argmax()

9

In [24]:
rand_arr.argmin()

1

## Shape

Shape is an attribute that arrays have (not a method):

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr.shape

(25,)

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr.dtype

dtype('int32')

In [34]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [36]:
arr.reshape(25,1).shape

(25, 1)

In [37]:
arr.dtype

dtype('int32')