# NumPy Indexing and Selection

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [7]:
# get a value by index
arr[2]

2

In [9]:
#get values by range through slicing
arr[2:6]

array([2, 3, 4, 5])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [10]:
#Setting a value with index range (Broadcasting)
arr[0:3] = 333

In [11]:
arr

array([333, 333, 333,   3,   4,   5,   6,   7,   8,   9,  10])

In [13]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
sliced_arr = arr[0:6]

In [16]:
sliced_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
sliced_arr[:] = 33

In [19]:
arr

array([33, 33, 33, 33, 33, 33,  6,  7,  8,  9, 10])

#### Note that by changing sliced_arr original array is also changed. This avoids memory problem.

In [20]:
#To get a copy, need to be explicit
arr_copy = arr.copy()
arr_copy

array([33, 33, 33, 33, 33, 33,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:] = 99

In [22]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [23]:
arr

array([33, 33, 33, 33, 33, 33,  6,  7,  8,  9, 10])

#### Note that both arrays are not independent of each other.

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [25]:
array_2D = np.array(([5,10,15],[10,20,30],[10,50,100]))

In [26]:
array_2D

array([[  5,  10,  15],
       [ 10,  20,  30],
       [ 10,  50, 100]])

In [27]:
 array_2D[1]

array([10, 20, 30])

In [29]:
# Getting individual element value
array_2D[1][0]

10

In [30]:
# Or you can get indivisual element value in another way__prefered way
array_2D[1,0]

10

In [41]:
# 2D array slicing
array_2D[:2,1:]

array([[10, 15],
       [20, 30]])

In [45]:
#Shape bottom row
array_2D[2,:]

array([ 10,  50, 100])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [46]:
#Set up matrix
arr2d = np.zeros((10,10))

In [47]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
#Length of array
arr_length = arr2d.shape
arr_length

(10, 10)

In [56]:
#Length of array
arr_length = arr2d.shape[1]
arr_length

10

In [57]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [58]:
# Fancy indexing allows the following
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [59]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [61]:
arr_2d = np.arange(50)

In [62]:
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [63]:
arr_2d = np.arange(50).reshape(5,10)

In [64]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
# target elements through indexing
arr_2d[2:4,6:8]

array([[26, 27],
       [36, 37]])